/**
 * Snapshot store client.
 *
 * Owns the SnapshotStore capture/materialize/merge lifecycle. Split
 * from electron/worldline-git.ts (issue #38).
 */
import { coreClient } from "./core-process.js";
import { join } from "node:path";
import { promotionIdentityPayload } from "./bound-promotion.js";
import type { PromotionFsIdentity } from "./bound-promotion.js";


/** One captured source state in the store. */
export interface SourceState {
  /** The synthetic commit oid in the store. */
  commit: string;
  /** The captured tree oid. */
  tree: string;
  /** The source HEAD the capture started from, or null when unborn. */
  head: string | null;
  /** The number of captured paths. */
  pathCount: number;
  /** New blob bytes written by this capture. */
  newBlobBytes: number;
  /** The lineage parent commit, or null for the root state. */
  parentCommit: string | null;
  /** Captured at. */
  ts: number;
}


interface CaptureBudget {
  maxPaths?: number;
  maxFileBytes?: number;
  maxNewBlobBytes?: number;
}


/** Exact lifecycle identity of one app-owned snapshot-store incarnation. */
export interface SnapshotStoreLifecycle {
  /** Random durable marker regenerated by every store-create. */
  generation: string;
  /** Device/inode of the store root at store-create. */
  identity: SnapshotStoreDirectoryIdentity;
  /** Device/inode identities of the bare Git child and stable internals. */
  git: SnapshotStoreGitLayout;
}


export interface SnapshotStoreDirectoryIdentity {
  dev: string;
  ino: string;
  type: "directory";
}


export interface SnapshotStoreGitLayout {
  git: SnapshotStoreDirectoryIdentity;
  objects: SnapshotStoreDirectoryIdentity;
  objectsInfo: SnapshotStoreDirectoryIdentity;
  objectsPack: SnapshotStoreDirectoryIdentity;
  refs: SnapshotStoreDirectoryIdentity;
  refsHeads: SnapshotStoreDirectoryIdentity;
  refsTags: SnapshotStoreDirectoryIdentity;
}


interface MaterializeOptions {
  preserveTopLevel?: string[];
  /** Bind the target to an already-opened native root identity. */
  boundRootIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}


/** Options for the descriptor-bound template/apply-state operations. */
interface BoundMaterializeOptions {
  /** Identity returned by the native directory allocator/opener. */
  boundRootIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}


/** Test seams for capture. The seams fire only in the spike suites. */
interface CaptureHooks {
  /** Rewrite a file after the core opens it, before the core reads it. */
  beforeRead?: Array<{ path: string; content: string; restoreMtime?: boolean }>;
  /** Rewrite a file after a full capture approves its index stat-cache entry. */
  afterCache?: Array<{ path: string; content: string; restoreMtime?: boolean }>;
  /** Fail after object publication but before the state ref is durable. */
  failStateRef?: boolean;
  /** Simulate libgit2 reporting failure after the state ref became visible. */
  failStateRefAfterWrite?: { markerPath: string };
}


/** The result of a three-way merge (WORLDLINES section 6.10). */
interface MergeResult {
  ok: boolean;
  /** The merged tree oid (valid only when ok). */
  tree: string | null;
  /** Conflicted paths, relative to the Git root. */
  conflicts: string[];
  /** The reason the merge was rejected before running. */
  reason?: string;
}


/** The result of a repository preflight (WORLDLINES section 4). */
interface PreflightResult {
  ok: boolean;
  reasons: string[];
}


/**
 * The app-owned snapshot store for one opened project session.
 */
export class SnapshotStore {
  readonly dir: string;
  /** The bare Git directory of the store. */
  readonly gitDir: string;
  /** The canonical source Git root this store serves. */
  readonly sourceRoot: string;
  /** The canonical common Git directory of the source repository. */
  readonly sourceGitDir: string;
  readonly objectFormat: "sha1" | "sha256";
  readonly lifecycle: SnapshotStoreLifecycle;

  private constructor(dir: string, sourceRoot: string, sourceGitDir: string, objectFormat: "sha1" | "sha256", lifecycle: SnapshotStoreLifecycle) {
    this.dir = dir;
    this.gitDir = join(dir, "git");
    this.sourceRoot = sourceRoot;
    this.sourceGitDir = sourceGitDir;
    this.objectFormat = objectFormat;
    this.lifecycle = lifecycle;
  }

  /** Create the store and link a read-only alternate to the source objects. */
  static async create(dir: string, sourceRoot: string, sourceGitDir: string, objectFormat: "sha1" | "sha256"): Promise<SnapshotStore> {
    const response = await coreClient.request({
      op: "store-create",
      storeDir: dir,
      sourceGitDir,
      objectFormat,
    });
    return new SnapshotStore(dir, sourceRoot, sourceGitDir, objectFormat, decodeSnapshotStoreLifecycle(response));
  }

  /** The request payload shared by every store op. */
  private payload(op: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
    return {
      op,
      storeDir: this.dir,
      sourceRoot: this.sourceRoot,
      sourceGitDir: this.sourceGitDir,
      objectFormat: this.objectFormat,
      ...extra,
      // Lifecycle fields are authoritative and must not be overridable by an
      // operation-specific extension payload.
      storeGeneration: this.lifecycle.generation,
      storeIdentity: this.lifecycle.identity,
      storeGitIdentity: this.lifecycle.git.git,
      storeGitObjectsIdentity: this.lifecycle.git.objects,
      storeGitObjectsInfoIdentity: this.lifecycle.git.objectsInfo,
      storeGitObjectsPackIdentity: this.lifecycle.git.objectsPack,
      storeGitRefsIdentity: this.lifecycle.git.refs,
      storeGitRefsHeadsIdentity: this.lifecycle.git.refsHeads,
      storeGitRefsTagsIdentity: this.lifecycle.git.refsTags,
    };
  }

  /** Send a store request and verify that its result is still this lifecycle. */
  private async requestBound(op: string, extra: Record<string, unknown> = {}): Promise<unknown> {
    const response = await coreClient.request(this.payload(op, extra));
    assertSnapshotStoreResult(response, this.lifecycle);
    return response;
  }

  /**
   * Capture the source working tree byte-for-byte.
   * Reads tracked, staged, unstaged, and non-ignored untracked files.
   * Accepts only regular files and symlinks.
   * Returns a synthetic commit in the store.
   */
  async capture(
    head: string | null,
    parentCommit: string | null,
    budget: CaptureBudget = {},
    hooks: CaptureHooks = {},
    source?: { root: string; gitDir: string },
  ): Promise<SourceState> {
    return this.requestBound("capture", {
      head,
      parentCommit,
      budget,
      hooks,
      captureRoot: source?.root,
      captureGitDir: source?.gitDir,
    }) as Promise<SourceState>;
  }

  /**
   * Incremental capture (WORLDLINES section 6.4): reuse the parent tree
   * and update only the hinted paths. The watcher hints are the delta;
   * the reconcile map catches missed events by comparing precomputed
   * blob hashes against the parent tree.
   */
  async captureIncremental(
    parentCommit: string,
    hints: string[],
    reconcile: Array<{ relPath: string; oid: string }>,
    budget: CaptureBudget = {},
    hooks: CaptureHooks = {},
    source?: { root: string; gitDir: string },
  ): Promise<SourceState> {
    return this.requestBound("capture-incremental", {
      parentCommit,
      hints,
      reconcile,
      budget,
      hooks,
      captureRoot: source?.root,
      captureGitDir: source?.gitDir,
    }) as Promise<SourceState>;
  }

  /**
   * Materialize a captured state into a directory.
   * Remove stale source paths and preserve only the requested runtime paths.
   */
  async materialize(stateCommit: string, targetDir: string, options: MaterializeOptions): Promise<void> {
    await this.requestBound("materialize", {
      stateId: stateCommit,
      targetDir,
      preserveTopLevel: options.preserveTopLevel,
      boundRootIdentity: promotionIdentityPayload(options.boundRootIdentity),
      ...(options.boundRootIdentity.capability ? { boundRootCapability: options.boundRootIdentity.capability } : {}),
      ...(options.testHook ? { testHook: options.testHook } : {}),
    });
  }

  /**
   * Three-way merge of the candidate head into the current primary state.
   * The commit graph provides the base: every state chains from the root
   * primary state, so its LCA is that root (WORLDLINES section 6.10).
   * Detects conflicts without writing any primary path.
   */
  async merge3(candidateCommit: string, primaryCommit: string): Promise<MergeResult> {
    const res = (await this.requestBound("merge3", { ours: candidateCommit, theirs: primaryCommit })) as { result: MergeResult };
    return res.result;
  }

  /** The changed paths between two store states. */
  async diffTree(stateA: string, stateB: string): Promise<Array<{ relPath: string; status: "created" | "modified" | "deleted" }>> {
    const res = (await this.requestBound("diff-tree", { stateA, stateB })) as { changes: Array<{ relPath: string; status: "created" | "modified" | "deleted" }> };
    return res.changes;
  }

  /** The tree paths of a state (for deletion detection). */
  async treePaths(state: string): Promise<Set<string>> {
    const res = (await this.requestBound("tree-paths", { stateId: state })) as { paths: string[] };
    return new Set(res.paths);
  }

  /** The target of a symlink at a state path, or null when not a link. */
  async symlinkTarget(state: string, relPath: string): Promise<string | null> {
    const res = (await this.requestBound("symlink-target", { stateId: state, relPath })) as { target: string | null };
    return res.target;
  }

  /** Read one blob from a state as bytes, or null when the path is absent. */
  async readBlob(state: string, relPath: string): Promise<Buffer | null> {
    const res = (await this.requestBound("read-blob", { stateId: state, relPath })) as { content: string | null };
    if (res.content === null) return null;
    return Buffer.from(res.content, "base64");
  }

  /** Remove a store-local state ref (eviction). */
  async unref(commit: string): Promise<void> {
    await this.requestBound("unref", { commit });
  }

  /**
   * Preflight the source repository for byte-exact capture.
   * Returns every failing condition with a stable reason string.
   */
  async preflightRepo(opts: { worldsRoot?: string } = {}): Promise<PreflightResult> {
    const res = (await coreClient.request({
      op: "preflight",
      sourceRoot: this.sourceRoot,
      sourceGitDir: this.sourceGitDir,
      worldsRoot: opts.worldsRoot ?? null,
    })) as { result: PreflightResult };
    return res.result;
  }

  /** Create the comparison template (init, base bytes, commit, pack). */
  async template(opts: { stateId: string; targetDir: string; sourceObjectsDir: string } & BoundMaterializeOptions): Promise<string> {
    const result = (await this.requestBound("template", {
      stateId: opts.stateId,
      targetDir: opts.targetDir,
      sourceObjectsDir: opts.sourceObjectsDir,
      boundRootIdentity: promotionIdentityPayload(opts.boundRootIdentity),
      ...(opts.boundRootIdentity.capability ? { boundRootCapability: opts.boundRootIdentity.capability } : {}),
      ...(opts.testHook ? { testHook: opts.testHook } : {}),
    })) as { commit?: unknown };
    if (typeof result.commit !== "string" || result.commit.length === 0) throw new Error("template operation returned no commit");
    return result.commit;
  }

  /** Apply a state over a candidate directory and commit it. */
  async applyState(opts: { stateId: string; targetDir: string; preserveTopLevel?: string[] } & BoundMaterializeOptions): Promise<void> {
    await this.requestBound("apply-state", {
      stateId: opts.stateId,
      targetDir: opts.targetDir,
      preserveTopLevel: opts.preserveTopLevel,
      boundRootIdentity: promotionIdentityPayload(opts.boundRootIdentity),
      ...(opts.boundRootIdentity.capability ? { boundRootCapability: opts.boundRootIdentity.capability } : {}),
      ...(opts.testHook ? { testHook: opts.testHook } : {}),
    });
  }

  /** Delete the whole store. Idempotent. */
  async destroy(): Promise<void> {
    const response = await coreClient.request(this.payload("store-destroy"));
    // A missing store is intentionally idempotent and returns an empty
    // payload.  When the store existed, core includes the deleted lifecycle
    // so a successful result cannot be confused with another generation.
    if (response && typeof response === "object" && !Array.isArray(response)) {
      const object = response as Record<string, unknown>;
      // Core returns only its normal response envelope when the path was
      // already absent; there is no lifecycle to validate in that case.
      // Any lifecycle-bearing result must still match this exact store.
      if (object.storeGeneration !== undefined || object.storeIdentity !== undefined) {
        assertSnapshotStoreResult(response, this.lifecycle);
      }
    }
  }
}


function decodeSnapshotStoreLifecycle(value: unknown): SnapshotStoreLifecycle {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("snapshot store create returned an invalid lifecycle");
  const object = value as Record<string, unknown>;
  const generation = object.storeGeneration;
  const identity = object.storeIdentity;
  if (typeof generation !== "string" || !/^[0-9a-f]{64}$/.test(generation) || !identity || typeof identity !== "object" || Array.isArray(identity)) {
    throw new Error("snapshot store create returned an invalid lifecycle");
  }
  const decodeDirectory = (raw: unknown, field: string): SnapshotStoreDirectoryIdentity => {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error(`snapshot store create returned an invalid ${field}`);
    const fields = raw as Record<string, unknown>;
    if (typeof fields.dev !== "string" || !/^\d+$/.test(fields.dev) || typeof fields.ino !== "string" || !/^\d+$/.test(fields.ino) || fields.type !== "directory") {
      throw new Error(`snapshot store create returned an invalid ${field}`);
    }
    return { dev: fields.dev, ino: fields.ino, type: "directory" };
  };
  const git = {
    git: decodeDirectory(object.storeGitIdentity, "storeGitIdentity"),
    objects: decodeDirectory(object.storeGitObjectsIdentity, "storeGitObjectsIdentity"),
    objectsInfo: decodeDirectory(object.storeGitObjectsInfoIdentity, "storeGitObjectsInfoIdentity"),
    objectsPack: decodeDirectory(object.storeGitObjectsPackIdentity, "storeGitObjectsPackIdentity"),
    refs: decodeDirectory(object.storeGitRefsIdentity, "storeGitRefsIdentity"),
    refsHeads: decodeDirectory(object.storeGitRefsHeadsIdentity, "storeGitRefsHeadsIdentity"),
    refsTags: decodeDirectory(object.storeGitRefsTagsIdentity, "storeGitRefsTagsIdentity"),
  } satisfies SnapshotStoreGitLayout;
  return { generation, identity: decodeDirectory(identity, "storeIdentity"), git };
}


function assertSnapshotStoreResult(value: unknown, expected: SnapshotStoreLifecycle): void {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("snapshot store operation returned an invalid result");
  const object = value as Record<string, unknown>;
  const candidate = object.storeGeneration !== undefined
    ? object
    : object.state && typeof object.state === "object" && !Array.isArray(object.state)
      ? object.state as Record<string, unknown>
      : object.result && typeof object.result === "object" && !Array.isArray(object.result)
        ? object.result as Record<string, unknown>
        : null;
  const observed = candidate ? decodeSnapshotStoreLifecycle(candidate) : null;
  const sameIdentity = (left: SnapshotStoreDirectoryIdentity, right: SnapshotStoreDirectoryIdentity) =>
    left.dev === right.dev && left.ino === right.ino && left.type === right.type;
  const sameGitLayout = observed && expected
    && sameIdentity(observed.git.git, expected.git.git)
    && sameIdentity(observed.git.objects, expected.git.objects)
    && sameIdentity(observed.git.objectsInfo, expected.git.objectsInfo)
    && sameIdentity(observed.git.objectsPack, expected.git.objectsPack)
    && sameIdentity(observed.git.refs, expected.git.refs)
    && sameIdentity(observed.git.refsHeads, expected.git.refsHeads)
    && sameIdentity(observed.git.refsTags, expected.git.refsTags);
  if (!observed || observed.generation !== expected.generation || !sameIdentity(observed.identity, expected.identity) || !sameGitLayout) {
    throw new Error("snapshot store operation returned a stale lifecycle");
  }
}
