/**
 * App-owned snapshot store client.
 *
 * The store is a bare Git repository outside the source repository. It
 * captures the source working-tree bytes byte-for-byte and reads source
 * objects through a read-only alternate. It never writes the user's Git
 * directory.
 *
 * Every operation runs in the Rust snapshot core (core-client.ts). This
 * module keeps only the paths, the object format, and the request
 * plumbing. It never spawns Git.
 */
import { execFile } from "node:child_process";
import { createHash, randomUUID } from "node:crypto";
import { lstatSync, readFileSync } from "node:fs";
import { basename, dirname, join, sep } from "node:path";
import { coreClient } from "./core-client.js";
import { SANDBOX_EXEC } from "./sandbox.js";

/** One captured source state in the store. */
export interface SourceState {
  /** The synthetic commit oid in the store. */
  commit: string;
  /** The captured tree oid. */
  tree: string;
  /** The source HEAD the capture started from, or null when unborn. */
  head: string | null;
  /** The number of captured paths. */
  pathCount: number;
  /** New blob bytes written by this capture. */
  newBlobBytes: number;
  /** The lineage parent commit, or null for the root state. */
  parentCommit: string | null;
  /** Captured at. */
  ts: number;
}

interface CaptureBudget {
  maxPaths?: number;
  maxFileBytes?: number;
  maxNewBlobBytes?: number;
}

/** Exact lifecycle identity of one app-owned snapshot-store incarnation. */
export interface SnapshotStoreLifecycle {
  /** Random durable marker regenerated by every store-create. */
  generation: string;
  /** Device/inode of the store root at store-create. */
  identity: SnapshotStoreDirectoryIdentity;
  /** Device/inode identities of the bare Git child and stable internals. */
  git: SnapshotStoreGitLayout;
}

export interface SnapshotStoreDirectoryIdentity {
  dev: string;
  ino: string;
  type: "directory";
}

export interface SnapshotStoreGitLayout {
  git: SnapshotStoreDirectoryIdentity;
  objects: SnapshotStoreDirectoryIdentity;
  objectsInfo: SnapshotStoreDirectoryIdentity;
  objectsPack: SnapshotStoreDirectoryIdentity;
  refs: SnapshotStoreDirectoryIdentity;
  refsHeads: SnapshotStoreDirectoryIdentity;
  refsTags: SnapshotStoreDirectoryIdentity;
}

interface MaterializeOptions {
  preserveTopLevel?: string[];
  /** Bind the target to an already-opened native root identity. */
  boundRootIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}

/** Options for the descriptor-bound template/apply-state operations. */
interface BoundMaterializeOptions {
  /** Identity returned by the native directory allocator/opener. */
  boundRootIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}

/** Test seams for capture. The seams fire only in the spike suites. */
interface CaptureHooks {
  /** Rewrite a file after the core opens it, before the core reads it. */
  beforeRead?: Array<{ path: string; content: string; restoreMtime?: boolean }>;
  /** Rewrite a file after a full capture approves its index stat-cache entry. */
  afterCache?: Array<{ path: string; content: string; restoreMtime?: boolean }>;
  /** Fail after object publication but before the state ref is durable. */
  failStateRef?: boolean;
  /** Simulate libgit2 reporting failure after the state ref became visible. */
  failStateRefAfterWrite?: { markerPath: string };
}

/** The result of a three-way merge (WORLDLINES section 6.10). */
interface MergeResult {
  ok: boolean;
  /** The merged tree oid (valid only when ok). */
  tree: string | null;
  /** Conflicted paths, relative to the Git root. */
  conflicts: string[];
  /** The reason the merge was rejected before running. */
  reason?: string;
}

/** The result of a repository preflight (WORLDLINES section 4). */
interface PreflightResult {
  ok: boolean;
  reasons: string[];
}

/**
 * The app-owned snapshot store for one opened project session.
 */
export class SnapshotStore {
  readonly dir: string;
  /** The bare Git directory of the store. */
  readonly gitDir: string;
  /** The canonical source Git root this store serves. */
  readonly sourceRoot: string;
  /** The canonical common Git directory of the source repository. */
  readonly sourceGitDir: string;
  readonly objectFormat: "sha1" | "sha256";
  readonly lifecycle: SnapshotStoreLifecycle;

  private constructor(dir: string, sourceRoot: string, sourceGitDir: string, objectFormat: "sha1" | "sha256", lifecycle: SnapshotStoreLifecycle) {
    this.dir = dir;
    this.gitDir = join(dir, "git");
    this.sourceRoot = sourceRoot;
    this.sourceGitDir = sourceGitDir;
    this.objectFormat = objectFormat;
    this.lifecycle = lifecycle;
  }

  /** Create the store and link a read-only alternate to the source objects. */
  static async create(dir: string, sourceRoot: string, sourceGitDir: string, objectFormat: "sha1" | "sha256"): Promise<SnapshotStore> {
    const response = await coreClient.request({
      op: "store-create",
      storeDir: dir,
      sourceGitDir,
      objectFormat,
    });
    return new SnapshotStore(dir, sourceRoot, sourceGitDir, objectFormat, decodeSnapshotStoreLifecycle(response));
  }

  /** The request payload shared by every store op. */
  private payload(op: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
    return {
      op,
      storeDir: this.dir,
      sourceRoot: this.sourceRoot,
      sourceGitDir: this.sourceGitDir,
      objectFormat: this.objectFormat,
      ...extra,
      // Lifecycle fields are authoritative and must not be overridable by an
      // operation-specific extension payload.
      storeGeneration: this.lifecycle.generation,
      storeIdentity: this.lifecycle.identity,
      storeGitIdentity: this.lifecycle.git.git,
      storeGitObjectsIdentity: this.lifecycle.git.objects,
      storeGitObjectsInfoIdentity: this.lifecycle.git.objectsInfo,
      storeGitObjectsPackIdentity: this.lifecycle.git.objectsPack,
      storeGitRefsIdentity: this.lifecycle.git.refs,
      storeGitRefsHeadsIdentity: this.lifecycle.git.refsHeads,
      storeGitRefsTagsIdentity: this.lifecycle.git.refsTags,
    };
  }

  /** Send a store request and verify that its result is still this lifecycle. */
  private async requestBound(op: string, extra: Record<string, unknown> = {}): Promise<unknown> {
    const response = await coreClient.request(this.payload(op, extra));
    assertSnapshotStoreResult(response, this.lifecycle);
    return response;
  }

  /**
   * Capture the source working tree byte-for-byte.
   * Reads tracked, staged, unstaged, and non-ignored untracked files.
   * Accepts only regular files and symlinks.
   * Returns a synthetic commit in the store.
   */
  async capture(
    head: string | null,
    parentCommit: string | null,
    budget: CaptureBudget = {},
    hooks: CaptureHooks = {},
    source?: { root: string; gitDir: string },
  ): Promise<SourceState> {
    return this.requestBound("capture", {
      head,
      parentCommit,
      budget,
      hooks,
      captureRoot: source?.root,
      captureGitDir: source?.gitDir,
    }) as Promise<SourceState>;
  }

  /**
   * Incremental capture (WORLDLINES section 6.4): reuse the parent tree
   * and update only the hinted paths. The watcher hints are the delta;
   * the reconcile map catches missed events by comparing precomputed
   * blob hashes against the parent tree.
   */
  async captureIncremental(
    parentCommit: string,
    hints: string[],
    reconcile: Array<{ relPath: string; oid: string }>,
    budget: CaptureBudget = {},
    hooks: CaptureHooks = {},
    source?: { root: string; gitDir: string },
  ): Promise<SourceState> {
    return this.requestBound("capture-incremental", {
      parentCommit,
      hints,
      reconcile,
      budget,
      hooks,
      captureRoot: source?.root,
      captureGitDir: source?.gitDir,
    }) as Promise<SourceState>;
  }

  /**
   * Materialize a captured state into a directory.
   * Remove stale source paths and preserve only the requested runtime paths.
   */
  async materialize(stateCommit: string, targetDir: string, options: MaterializeOptions): Promise<void> {
    await this.requestBound("materialize", {
      stateId: stateCommit,
      targetDir,
      preserveTopLevel: options.preserveTopLevel,
      boundRootIdentity: promotionIdentityPayload(options.boundRootIdentity),
      ...(options.boundRootIdentity.capability ? { boundRootCapability: options.boundRootIdentity.capability } : {}),
      ...(options.testHook ? { testHook: options.testHook } : {}),
    });
  }

  /**
   * Three-way merge of the candidate head into the current primary state.
   * The commit graph provides the base: every state chains from the root
   * primary state, so its LCA is that root (WORLDLINES section 6.10).
   * Detects conflicts without writing any primary path.
   */
  async merge3(candidateCommit: string, primaryCommit: string): Promise<MergeResult> {
    const res = (await this.requestBound("merge3", { ours: candidateCommit, theirs: primaryCommit })) as { result: MergeResult };
    return res.result;
  }

  /** The changed paths between two store states. */
  async diffTree(stateA: string, stateB: string): Promise<Array<{ relPath: string; status: "created" | "modified" | "deleted" }>> {
    const res = (await this.requestBound("diff-tree", { stateA, stateB })) as { changes: Array<{ relPath: string; status: "created" | "modified" | "deleted" }> };
    return res.changes;
  }

  /** The tree paths of a state (for deletion detection). */
  async treePaths(state: string): Promise<Set<string>> {
    const res = (await this.requestBound("tree-paths", { stateId: state })) as { paths: string[] };
    return new Set(res.paths);
  }

  /** The target of a symlink at a state path, or null when not a link. */
  async symlinkTarget(state: string, relPath: string): Promise<string | null> {
    const res = (await this.requestBound("symlink-target", { stateId: state, relPath })) as { target: string | null };
    return res.target;
  }

  /** Read one blob from a state as bytes, or null when the path is absent. */
  async readBlob(state: string, relPath: string): Promise<Buffer | null> {
    const res = (await this.requestBound("read-blob", { stateId: state, relPath })) as { content: string | null };
    if (res.content === null) return null;
    return Buffer.from(res.content, "base64");
  }

  /** Remove a store-local state ref (eviction). */
  async unref(commit: string): Promise<void> {
    await this.requestBound("unref", { commit });
  }

  /**
   * Preflight the source repository for byte-exact capture.
   * Returns every failing condition with a stable reason string.
   */
  async preflightRepo(opts: { worldsRoot?: string } = {}): Promise<PreflightResult> {
    const res = (await coreClient.request({
      op: "preflight",
      sourceRoot: this.sourceRoot,
      sourceGitDir: this.sourceGitDir,
      worldsRoot: opts.worldsRoot ?? null,
    })) as { result: PreflightResult };
    return res.result;
  }

  /** Create the comparison template (init, base bytes, commit, pack). */
  async template(opts: { stateId: string; targetDir: string; sourceObjectsDir: string } & BoundMaterializeOptions): Promise<string> {
    const result = (await this.requestBound("template", {
      stateId: opts.stateId,
      targetDir: opts.targetDir,
      sourceObjectsDir: opts.sourceObjectsDir,
      boundRootIdentity: promotionIdentityPayload(opts.boundRootIdentity),
      ...(opts.boundRootIdentity.capability ? { boundRootCapability: opts.boundRootIdentity.capability } : {}),
      ...(opts.testHook ? { testHook: opts.testHook } : {}),
    })) as { commit?: unknown };
    if (typeof result.commit !== "string" || result.commit.length === 0) throw new Error("template operation returned no commit");
    return result.commit;
  }

  /** Apply a state over a candidate directory and commit it. */
  async applyState(opts: { stateId: string; targetDir: string; preserveTopLevel?: string[] } & BoundMaterializeOptions): Promise<void> {
    await this.requestBound("apply-state", {
      stateId: opts.stateId,
      targetDir: opts.targetDir,
      preserveTopLevel: opts.preserveTopLevel,
      boundRootIdentity: promotionIdentityPayload(opts.boundRootIdentity),
      ...(opts.boundRootIdentity.capability ? { boundRootCapability: opts.boundRootIdentity.capability } : {}),
      ...(opts.testHook ? { testHook: opts.testHook } : {}),
    });
  }

  /** Delete the whole store. Idempotent. */
  async destroy(): Promise<void> {
    const response = await coreClient.request(this.payload("store-destroy"));
    // A missing store is intentionally idempotent and returns an empty
    // payload.  When the store existed, core includes the deleted lifecycle
    // so a successful result cannot be confused with another generation.
    if (response && typeof response === "object" && !Array.isArray(response)) {
      const object = response as Record<string, unknown>;
      // Core returns only its normal response envelope when the path was
      // already absent; there is no lifecycle to validate in that case.
      // Any lifecycle-bearing result must still match this exact store.
      if (object.storeGeneration !== undefined || object.storeIdentity !== undefined) {
        assertSnapshotStoreResult(response, this.lifecycle);
      }
    }
  }
}

function decodeSnapshotStoreLifecycle(value: unknown): SnapshotStoreLifecycle {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("snapshot store create returned an invalid lifecycle");
  const object = value as Record<string, unknown>;
  const generation = object.storeGeneration;
  const identity = object.storeIdentity;
  if (typeof generation !== "string" || !/^[0-9a-f]{64}$/.test(generation) || !identity || typeof identity !== "object" || Array.isArray(identity)) {
    throw new Error("snapshot store create returned an invalid lifecycle");
  }
  const decodeDirectory = (raw: unknown, field: string): SnapshotStoreDirectoryIdentity => {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) throw new Error(`snapshot store create returned an invalid ${field}`);
    const fields = raw as Record<string, unknown>;
    if (typeof fields.dev !== "string" || !/^\d+$/.test(fields.dev) || typeof fields.ino !== "string" || !/^\d+$/.test(fields.ino) || fields.type !== "directory") {
      throw new Error(`snapshot store create returned an invalid ${field}`);
    }
    return { dev: fields.dev, ino: fields.ino, type: "directory" };
  };
  const git = {
    git: decodeDirectory(object.storeGitIdentity, "storeGitIdentity"),
    objects: decodeDirectory(object.storeGitObjectsIdentity, "storeGitObjectsIdentity"),
    objectsInfo: decodeDirectory(object.storeGitObjectsInfoIdentity, "storeGitObjectsInfoIdentity"),
    objectsPack: decodeDirectory(object.storeGitObjectsPackIdentity, "storeGitObjectsPackIdentity"),
    refs: decodeDirectory(object.storeGitRefsIdentity, "storeGitRefsIdentity"),
    refsHeads: decodeDirectory(object.storeGitRefsHeadsIdentity, "storeGitRefsHeadsIdentity"),
    refsTags: decodeDirectory(object.storeGitRefsTagsIdentity, "storeGitRefsTagsIdentity"),
  } satisfies SnapshotStoreGitLayout;
  return { generation, identity: decodeDirectory(identity, "storeIdentity"), git };
}

function assertSnapshotStoreResult(value: unknown, expected: SnapshotStoreLifecycle): void {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("snapshot store operation returned an invalid result");
  const object = value as Record<string, unknown>;
  const candidate = object.storeGeneration !== undefined
    ? object
    : object.state && typeof object.state === "object" && !Array.isArray(object.state)
      ? object.state as Record<string, unknown>
      : object.result && typeof object.result === "object" && !Array.isArray(object.result)
        ? object.result as Record<string, unknown>
        : null;
  const observed = candidate ? decodeSnapshotStoreLifecycle(candidate) : null;
  const sameIdentity = (left: SnapshotStoreDirectoryIdentity, right: SnapshotStoreDirectoryIdentity) =>
    left.dev === right.dev && left.ino === right.ino && left.type === right.type;
  const sameGitLayout = observed && expected
    && sameIdentity(observed.git.git, expected.git.git)
    && sameIdentity(observed.git.objects, expected.git.objects)
    && sameIdentity(observed.git.objectsInfo, expected.git.objectsInfo)
    && sameIdentity(observed.git.objectsPack, expected.git.objectsPack)
    && sameIdentity(observed.git.refs, expected.git.refs)
    && sameIdentity(observed.git.refsHeads, expected.git.refsHeads)
    && sameIdentity(observed.git.refsTags, expected.git.refsTags);
  if (!observed || observed.generation !== expected.generation || !sameIdentity(observed.identity, expected.identity) || !sameGitLayout) {
    throw new Error("snapshot store operation returned a stale lifecycle");
  }
}

/** Decimal device/inode identity used by the native promotion boundary. */
export interface PromotionFsIdentity {
  dev: string;
  ino: string;
  /** Opaque capability retained by the long-lived native core process. */
  capability?: string;
}

export interface BoundPromotionJournalRead {
  journalRoot: string;
  journalRootIdentity: PromotionFsIdentity;
  operationName: string;
  operationIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}

export type BoundPromotionExpectedState =
  | { type: "file"; mode: number; size: string; sha256: string }
  | { type: "symlink"; target: string };

export interface BoundPromotionExpectedLeaf {
  identity: PromotionFsIdentity;
  state: BoundPromotionExpectedState;
}

export interface BoundPromotionExpectedMissing {
  state: { type: "missing" };
}

export interface BoundPromotionDirectoryResult {
  path: string;
  identity: PromotionFsIdentity;
}

export interface BoundPromotionLeafResult {
  leaf: BoundPromotionExpectedLeaf;
}

export type BoundPromotionTransitionRequest = {
  primaryRoot: string;
  primaryRootIdentity: PromotionFsIdentity;
  destinationComponents: string[];
  parentIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
  transition:
    | {
        kind: "exchange";
        sourceName: string;
        expectedSource: BoundPromotionExpectedLeaf;
        expectedDestination: BoundPromotionExpectedLeaf;
      }
      | {
        kind: "retire";
        retainedName: string;
        expectedDestination: BoundPromotionExpectedLeaf;
        retainedRoot?: string;
        retainedRootIdentity?: PromotionFsIdentity;
        retainedComponents?: string[];
        retainedParentIdentity?: PromotionFsIdentity;
      }
    | {
        kind: "install";
        sourceRoot: string;
        sourceRootIdentity: PromotionFsIdentity;
        sourceComponents: string[];
        sourceParentIdentity: PromotionFsIdentity;
        expectedSource: BoundPromotionExpectedLeaf;
        expectedDestination: BoundPromotionExpectedLeaf | BoundPromotionExpectedMissing;
      };
};

export interface BoundPromotionTransitionResult {
  outcome: "applied" | "conflict-after-mutation";
  transition: "exchange" | "retire" | "install";
  durable: boolean;
  retainedName: string | null;
  error: string | null;
}

function decodeBoundPromotionBytes(response: unknown): Buffer {
  if (!response || typeof response !== "object" || Array.isArray(response)) throw new Error("invalid bound promotion journal response");
  const value = response as Record<string, unknown>;
  if (typeof value.content !== "string" || !/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value.content)) {
    throw new Error("invalid bound promotion journal bytes");
  }
  if (!Number.isSafeInteger(value.byteLength) || Number(value.byteLength) < 0) throw new Error("invalid bound promotion journal byte length");
  const bytes = Buffer.from(value.content, "base64");
  if (bytes.byteLength !== Number(value.byteLength)) throw new Error("bound promotion journal byte length mismatch");
  return bytes;
}

/** Read journal bytes below an operation directory held by the Rust core. */
export async function readBoundPromotionJournal(options: BoundPromotionJournalRead): Promise<Buffer> {
  const response = await coreClient.request({
    op: "promotion-bound-read-journal",
    journalRoot: options.journalRoot,
    journalRootIdentity: { dev: options.journalRootIdentity.dev, ino: options.journalRootIdentity.ino },
    ...(options.journalRootIdentity.capability ? { journalRootCapability: options.journalRootIdentity.capability } : {}),
    operationName: options.operationName,
    operationIdentity: options.operationIdentity,
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
  return decodeBoundPromotionBytes(response);
}

/** Read one bounded private file below an identity-bound parent. */
export async function boundPromotionReadFile(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components: string[];
  parentIdentity: PromotionFsIdentity;
  expectedIdentity?: PromotionFsIdentity;
  maxBytes?: number;
}): Promise<{ content: Buffer; identity: PromotionFsIdentity }> {
  const response = await coreClient.request({
    op: "promotion-bound-read-file",
    root: options.root,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
    components: options.components,
    parentIdentity: options.parentIdentity,
    ...(options.expectedIdentity ? { expectedIdentity: { dev: options.expectedIdentity.dev, ino: options.expectedIdentity.ino } } : {}),
    ...(options.maxBytes === undefined ? {} : { maxBytes: options.maxBytes }),
  });
  const value = response as Record<string, unknown>;
  const content = decodeBoundPromotionBytes(response);
  const identity = decodePromotionIdentity(value.identity, "bound promotion read file identity");
  return { content, identity };
}

/** Execute one preservation-first, descriptor-relative promotion transition. */
export async function boundPromotionTransition(options: BoundPromotionTransitionRequest): Promise<BoundPromotionTransitionResult> {
  const transition = options.transition;
  const payload: Record<string, unknown> = {
    ...options,
    primaryRootIdentity: promotionIdentityPayload(options.primaryRootIdentity),
    ...(options.primaryRootIdentity.capability ? { primaryRootCapability: options.primaryRootIdentity.capability } : {}),
  };
  if (transition.kind === "install") {
    payload.transition = {
      ...transition,
      sourceRootIdentity: promotionIdentityPayload(transition.sourceRootIdentity),
      ...(transition.sourceRootIdentity.capability ? { sourceRootCapability: transition.sourceRootIdentity.capability } : {}),
    };
  } else if (transition.kind === "retire" && transition.retainedRootIdentity) {
    payload.transition = {
      ...transition,
      retainedRootIdentity: promotionIdentityPayload(transition.retainedRootIdentity),
      ...(transition.retainedRootIdentity.capability ? { retainedRootCapability: transition.retainedRootIdentity.capability } : {}),
    };
  }
  const response = (await coreClient.request({
    op: "promotion-bound-transition",
    ...payload,
  })) as { result?: unknown };
  const result = response?.result;
  if (!result || typeof result !== "object" || Array.isArray(result)) throw new Error("invalid bound promotion transition response");
  const value = result as Record<string, unknown>;
  if (
    (value.outcome !== "applied" && value.outcome !== "conflict-after-mutation")
    || (value.transition !== "exchange" && value.transition !== "retire" && value.transition !== "install")
    || typeof value.durable !== "boolean"
    || (value.retainedName !== null && typeof value.retainedName !== "string")
    || (value.error !== null && typeof value.error !== "string")
  ) {
    throw new Error("invalid bound promotion transition result");
  }
  return {
    outcome: value.outcome,
    transition: value.transition,
    durable: value.durable,
    retainedName: value.retainedName,
    error: value.error,
  };
}

function decodePromotionIdentity(value: unknown, field: string): PromotionFsIdentity {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`invalid ${field}`);
  const object = value as Record<string, unknown>;
  if (typeof object.dev !== "string" || !/^\d+$/.test(object.dev) || typeof object.ino !== "string" || !/^\d+$/.test(object.ino)) {
    throw new Error(`invalid ${field}`);
  }
  return { dev: object.dev, ino: object.ino };
}

function promotionIdentityPayload(identity: PromotionFsIdentity): { dev: string; ino: string } {
  return { dev: identity.dev, ino: identity.ino };
}

function decodePromotionLeaf(value: unknown, field: string): BoundPromotionExpectedLeaf {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`invalid ${field}`);
  const object = value as Record<string, unknown>;
  const identity = decodePromotionIdentity(object.identity, `${field}.identity`);
  if (!object.state || typeof object.state !== "object" || Array.isArray(object.state)) throw new Error(`invalid ${field}.state`);
  const state = object.state as Record<string, unknown>;
  if (state.type === "file" && typeof state.mode === "number" && Number.isInteger(state.mode) && state.mode >= 0 && state.mode <= 0o777 && typeof state.size === "string" && /^\d+$/.test(state.size) && typeof state.sha256 === "string" && /^[0-9a-f]{64}$/.test(state.sha256)) {
    return { identity, state: { type: "file", mode: state.mode, size: state.size, sha256: state.sha256 } };
  }
  if (state.type === "symlink" && typeof state.target === "string" && !state.target.includes("\0")) {
    return { identity, state: { type: "symlink", target: state.target } };
  }
  throw new Error(`invalid ${field}.state`);
}

function decodePromotionResponse(response: unknown): Record<string, unknown> {
  if (!response || typeof response !== "object" || Array.isArray(response)) throw new Error("invalid bound promotion response");
  const result = (response as Record<string, unknown>).result;
  if (!result || typeof result !== "object" || Array.isArray(result)) throw new Error("invalid bound promotion result");
  return result as Record<string, unknown>;
}

/** Open one trusted absolute directory in the native boundary. */
export async function boundPromotionOpenDirectory(options: {
  path: string;
  expectedIdentity?: PromotionFsIdentity;
  capability?: string;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<PromotionFsIdentity> {
  let expectedIdentity = options.expectedIdentity;
  if (!expectedIdentity && !options.capability) {
    const metadata = lstatSync(options.path, { bigint: true });
    if (!metadata.isDirectory() || metadata.isSymbolicLink()) throw new Error("bound promotion directory is not a real directory");
    expectedIdentity = { dev: String(metadata.dev), ino: String(metadata.ino) };
  }
  const response = await coreClient.request({
    op: "promotion-bound-open-directory",
    path: options.path,
    ...(expectedIdentity ? { expectedIdentity: { dev: expectedIdentity.dev, ino: expectedIdentity.ino } } : {}),
    ...(options.capability ? { capability: options.capability } : {}),
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
  const result = decodePromotionResponse(response);
  const identity = decodePromotionIdentity(result.identity, "bound promotion opened directory identity");
  if (typeof result.capability !== "string" || result.capability.length === 0) throw new Error("bound promotion opened directory capability is missing");
  return { ...identity, capability: result.capability };
}

/** List immediate child directories with identities captured by Core. */
export async function boundPromotionListDirectories(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
}): Promise<Array<{ name: string; identity: PromotionFsIdentity }>> {
  const response = await coreClient.request({
    op: "promotion-bound-list-directories",
    root: options.root,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
  });
  const result = decodePromotionResponse(response);
  if (!Array.isArray(result.entries)) throw new Error("invalid bound promotion directory entries");
  return result.entries.map((entry, index) => {
    if (!entry || typeof entry !== "object" || Array.isArray(entry)) throw new Error(`invalid bound promotion directory entry ${index}`);
    const value = entry as Record<string, unknown>;
    if (typeof value.name !== "string" || value.name.length === 0 || value.name.includes("/") || value.name.includes("\\") || value.name === "." || value.name === "..") {
      throw new Error(`invalid bound promotion directory name ${index}`);
    }
    return { name: value.name, identity: decodePromotionIdentity(value.identity, `bound promotion directory identity ${index}`) };
  });
}

/** List immediate entries with native namespace identities for cleanup. */
export async function boundPromotionListEntries(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
}): Promise<Array<{ name: string; identity: PromotionFsIdentity; kind: "directory" | "file" | "symlink" | "other" }>> {
  const response = await coreClient.request({
    op: "promotion-bound-list-entries",
    root: options.root,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
  });
  const result = decodePromotionResponse(response);
  if (!Array.isArray(result.entries)) throw new Error("invalid bound promotion entries");
  return result.entries.map((entry, index) => {
    if (!entry || typeof entry !== "object" || Array.isArray(entry)) throw new Error(`invalid bound promotion entry ${index}`);
    const value = entry as Record<string, unknown>;
    if (typeof value.name !== "string" || value.name.length === 0 || value.name.includes("/") || value.name.includes("\\") || value.name === "." || value.name === "..") {
      throw new Error(`invalid bound promotion entry name ${index}`);
    }
    if (value.kind !== "directory" && value.kind !== "file" && value.kind !== "symlink" && value.kind !== "other") {
      throw new Error(`invalid bound promotion entry kind ${index}`);
    }
    return {
      name: value.name,
      identity: decodePromotionIdentity(value.identity, `bound promotion entry identity ${index}`),
      kind: value.kind,
    };
  });
}

/** Probe/create a directory chain below a natively bound root. */
export async function boundPromotionPrepareDirectory(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components?: string[];
  createMissing?: boolean;
  allowMissing?: boolean;
  expectedMissingAt?: number;
  expectedChain?: PromotionFsIdentity[];
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<{ identity: PromotionFsIdentity | null; missingAt: number | null; chain: PromotionFsIdentity[] }> {
  const response = await coreClient.request({
    op: "promotion-bound-prepare-directory",
    root: options.root,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
    components: options.components ?? [],
    ...(options.createMissing === undefined ? {} : { createMissing: options.createMissing }),
    ...(options.allowMissing === undefined ? {} : { allowMissing: options.allowMissing }),
    ...(options.expectedMissingAt === undefined ? {} : { expectedMissingAt: options.expectedMissingAt }),
    ...(options.expectedChain === undefined ? {} : { expectedChain: options.expectedChain }),
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
  const result = decodePromotionResponse(response);
  let identity: PromotionFsIdentity | null = null;
  if (result.identity !== null && result.identity !== undefined) {
    identity = decodePromotionIdentity(result.identity, "bound promotion prepared directory identity");
    const capability = (result.identity as Record<string, unknown>).capability;
    if (typeof capability === "string" && capability.length > 0) identity.capability = capability;
  }
  const rawMissingAt = result.missingAt;
  if (rawMissingAt !== null && rawMissingAt !== undefined && (!Number.isSafeInteger(rawMissingAt) || Number(rawMissingAt) < 0)) {
    throw new Error("invalid bound promotion directory missingAt");
  }
  if (!Array.isArray(result.chain)) throw new Error("invalid bound promotion directory chain");
  const chain = result.chain.map((value, index) => decodePromotionIdentity(value, `bound promotion directory chain ${index}`));
  return { identity, missingAt: rawMissingAt === null || rawMissingAt === undefined ? null : Number(rawMissingAt), chain };
}

/** Ensure an absolute directory chain through the native root descriptor. */
export async function boundPromotionEnsureDirectory(options: {
  path: string;
  expectedIdentity?: PromotionFsIdentity;
  capability?: string;
  trustedParent?: { path: string; identity: PromotionFsIdentity; name: string };
  /** Explicit legacy/new-root transaction state; never inferred from a path. */
  bootstrapExisting?: boolean;
  provenance?: {
    name: string;
    parent: { path: string; identity: PromotionFsIdentity };
  };
  marker?: { name: string; content: Buffer; mode?: number };
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<PromotionFsIdentity> {
  const response = await coreClient.request({
    op: "promotion-bound-ensure-directory",
    path: options.path,
    ...(options.expectedIdentity ? { expectedIdentity: { dev: options.expectedIdentity.dev, ino: options.expectedIdentity.ino } } : {}),
    ...(options.capability ? { capability: options.capability } : {}),
    ...(options.trustedParent ? {
      trustedParent: {
        path: options.trustedParent.path,
        identity: { dev: options.trustedParent.identity.dev, ino: options.trustedParent.identity.ino },
        name: options.trustedParent.name,
        ...(options.trustedParent.identity.capability ? { capability: options.trustedParent.identity.capability } : {}),
      },
    } : {}),
    ...(options.bootstrapExisting === undefined ? {} : { bootstrapExisting: options.bootstrapExisting }),
    ...(options.provenance ? {
      provenance: {
        name: options.provenance.name,
        parent: {
          path: options.provenance.parent.path,
          identity: promotionIdentityPayload(options.provenance.parent.identity),
          ...(options.provenance.parent.identity.capability ? { capability: options.provenance.parent.identity.capability } : {}),
        },
      },
    } : {}),
    ...(options.marker ? {
      marker: {
        name: options.marker.name,
        content: options.marker.content.toString("base64"),
        ...(options.marker.mode === undefined ? {} : { mode: options.marker.mode }),
      },
    } : {}),
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
  const result = decodePromotionResponse(response);
  const identity = decodePromotionIdentity(result.identity, "bound promotion ensured directory identity");
  const capability = (result.identity as Record<string, unknown>).capability ?? result.capability;
  if (typeof capability === "string" && capability.length > 0) identity.capability = capability;
  return identity;
}

/** Create or open one directory below an identity-bound directory. */
export async function boundPromotionCreateDirectory(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components: string[];
  parentIdentity: PromotionFsIdentity;
  requireMissing?: boolean;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<PromotionFsIdentity> {
  const result = decodePromotionResponse(await coreClient.request({
    op: "promotion-bound-create-directory",
    ...options,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
  }));
  const identity = decodePromotionIdentity(result.identity, "bound promotion directory identity");
  const capability = (result.identity as Record<string, unknown>).capability;
  if (typeof capability === "string" && capability.length > 0) identity.capability = capability;
  return identity;
}

/** Copy a complete tree between two identity-bound directories. */
export async function boundPromotionCopyTree(options: {
  sourceRoot: string;
  sourceRootIdentity: PromotionFsIdentity;
  destinationRoot: string;
  destinationRootIdentity: PromotionFsIdentity;
  maxBytes?: number;
  maxWorkBytes?: number;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<{ bytes: number; entries: number; workBytes: number }> {
  const result = decodePromotionResponse(await coreClient.request({
    op: "promotion-bound-copy-tree",
    sourceRoot: options.sourceRoot,
    sourceRootIdentity: promotionIdentityPayload(options.sourceRootIdentity),
    ...(options.sourceRootIdentity.capability ? { sourceRootCapability: options.sourceRootIdentity.capability } : {}),
    destinationRoot: options.destinationRoot,
    destinationRootIdentity: promotionIdentityPayload(options.destinationRootIdentity),
    ...(options.destinationRootIdentity.capability ? { destinationRootCapability: options.destinationRootIdentity.capability } : {}),
    ...(options.maxBytes === undefined ? {} : { maxBytes: options.maxBytes }),
    ...(options.maxWorkBytes === undefined ? {} : { maxWorkBytes: options.maxWorkBytes }),
    ...(options.testHook ? { testHook: options.testHook } : {}),
  }));
  if (
    !Number.isSafeInteger(result.bytes) || Number(result.bytes) < 0
    || !Number.isSafeInteger(result.entries) || Number(result.entries) < 0
    || !Number.isSafeInteger(result.workBytes) || Number(result.workBytes) < 0
  ) {
    throw new Error("invalid bound promotion tree copy result");
  }
  return { bytes: Number(result.bytes), entries: Number(result.entries), workBytes: Number(result.workBytes) };
}

/** Write one bounded evidence/journal file through an identity-bound parent. */
export async function boundPromotionWriteFile(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components: string[];
  parentIdentity: PromotionFsIdentity;
  expectedDestination: BoundPromotionExpectedLeaf | BoundPromotionExpectedMissing;
  content: Buffer;
  mode?: number;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<BoundPromotionExpectedLeaf> {
  const response = await coreClient.request({
    op: "promotion-bound-write-file",
    root: options.root,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
    components: options.components,
    parentIdentity: options.parentIdentity,
    expectedDestination: options.expectedDestination,
    content: options.content.toString("base64"),
    ...(options.mode === undefined ? {} : { mode: options.mode }),
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
  const result = decodePromotionResponse(response);
  return decodePromotionLeaf(result.leaf, "bound promotion written leaf");
}

/**
 * Replace one small private file below an already-bound directory.  The
 * existing leaf is authenticated by the native read before the write; a
 * missing leaf is passed as an explicit missing expectation.  This keeps
 * mailbox/provenance bookkeeping on the same descriptor-bound owner as
 * evidence files instead of falling back to a pathname write.
 */
export async function writeBoundOwnedFile(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components: string[];
  parentIdentity: PromotionFsIdentity;
  content: Buffer;
  mode?: number;
  maxBytes?: number;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<BoundPromotionExpectedLeaf> {
  let expected: BoundPromotionExpectedLeaf | BoundPromotionExpectedMissing = { state: { type: "missing" } };
  try {
    const current = await boundPromotionReadFile({
      root: options.root,
      rootIdentity: options.rootIdentity,
      components: options.components,
      parentIdentity: options.parentIdentity,
      ...(options.maxBytes === undefined ? {} : { maxBytes: options.maxBytes }),
    });
    let mode = options.mode ?? 0o600;
    try {
      mode = lstatSync(join(options.root, ...options.components)).mode & 0o777;
    } catch {
      /* Native read authenticated the existing leaf; keep the safe default. */
    }
    expected = {
      identity: current.identity,
      state: {
        type: "file",
        mode,
        size: String(current.content.byteLength),
        sha256: createHash("sha256").update(current.content).digest("hex"),
      },
    };
  } catch (error) {
    try {
      lstatSync(join(options.root, ...options.components));
      throw error;
    } catch (probeError) {
      if (probeError === error) throw error;
      if (probeError && typeof probeError === "object" && "code" in probeError && probeError.code === "ENOENT") {
        expected = { state: { type: "missing" } };
      } else {
        throw error;
      }
    }
  }
  return boundPromotionWriteFile({
    root: options.root,
    rootIdentity: options.rootIdentity,
    components: options.components,
    parentIdentity: options.parentIdentity,
    expectedDestination: expected,
    content: options.content,
    mode: options.mode ?? 0o600,
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
}

/**
 * Write one small JSON bookkeeping file through an identity-bound root. The
 * native write is deliberately direct: a crash can leave malformed JSON, but
 * the next reader rebuilds it fail-closed. The old leaf identity and content
 * hash are supplied when replacing an existing file so a root/leaf ABA cannot
 * redirect the write to a pathname replacement.
 */
export async function boundPromotionWriteJsonFile(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components: string[];
  parentIdentity: PromotionFsIdentity;
  value: unknown;
  maxBytes: number;
  mode?: number;
}): Promise<BoundPromotionExpectedLeaf> {
  const content = Buffer.from(JSON.stringify(options.value));
  if (!Number.isSafeInteger(options.maxBytes) || options.maxBytes < 0 || content.byteLength > options.maxBytes) {
    throw new Error("bound promotion JSON exceeds its byte budget");
  }
  let expected: BoundPromotionExpectedLeaf | BoundPromotionExpectedMissing = { state: { type: "missing" } };
  try {
    const existing = await boundPromotionReadFile({
      root: options.root,
      rootIdentity: options.rootIdentity,
      components: options.components,
      parentIdentity: options.parentIdentity,
      maxBytes: options.maxBytes,
    });
    let mode = options.mode ?? 0o600;
    try {
      const info = lstatSync(join(options.root, ...options.components));
      mode = info.mode & 0o777;
    } catch {
      // Native read already authenticated the existing leaf; retain the
      // default mode if a concurrent pathname observation is unavailable.
    }
    expected = {
      identity: existing.identity,
      state: {
        type: "file",
        mode,
        size: String(existing.content.byteLength),
        sha256: createHash("sha256").update(existing.content).digest("hex"),
      },
    };
  } catch (error) {
    try {
      const info = lstatSync(join(options.root, ...options.components));
      if (info.isFile() && !info.isSymbolicLink()) throw error;
    } catch (probeError) {
      if (probeError === error) throw error;
      if (probeError && typeof probeError === "object" && "code" in probeError && probeError.code === "ENOENT") {
        expected = { state: { type: "missing" } };
      } else {
        throw error;
      }
    }
  }
  return boundPromotionWriteFile({
    root: options.root,
    rootIdentity: options.rootIdentity,
    components: options.components,
    parentIdentity: options.parentIdentity,
    expectedDestination: expected,
    content,
    mode: options.mode ?? 0o600,
  });
}

/** Copy a regular file between identity-bound parents. */
export async function boundPromotionCopyFile(options: {
  sourceRoot: string;
  sourceRootIdentity: PromotionFsIdentity;
  sourceComponents: string[];
  sourceParentIdentity: PromotionFsIdentity;
  expectedSource: BoundPromotionExpectedLeaf;
  destinationRoot: string;
  destinationRootIdentity: PromotionFsIdentity;
  destinationComponents: string[];
  destinationParentIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<BoundPromotionExpectedLeaf> {
  const response = await coreClient.request({
    op: "promotion-bound-copy-file",
    ...options,
    sourceRootIdentity: { dev: options.sourceRootIdentity.dev, ino: options.sourceRootIdentity.ino },
    ...(options.sourceRootIdentity.capability ? { sourceRootCapability: options.sourceRootIdentity.capability } : {}),
    destinationRootIdentity: { dev: options.destinationRootIdentity.dev, ino: options.destinationRootIdentity.ino },
    ...(options.destinationRootIdentity.capability ? { destinationRootCapability: options.destinationRootIdentity.capability } : {}),
    expectedSource: options.expectedSource,
    expectedDestination: { state: { type: "missing" } },
  });
  const result = decodePromotionResponse(response);
  return decodePromotionLeaf(result.leaf, "bound promotion copied leaf");
}

/** Create a symlink leaf below an identity-bound parent. */
export async function boundPromotionCreateSymlink(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components: string[];
  parentIdentity: PromotionFsIdentity;
  target: string;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<BoundPromotionExpectedLeaf> {
  const result = decodePromotionResponse(await coreClient.request({
    op: "promotion-bound-create-symlink",
    ...options,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
  }));
  return decodePromotionLeaf(result.leaf, "bound promotion symlink leaf");
}

/** Move a complete core-session bundle without pathname-following. */
export async function boundPromotionInstallDirectory(options: {
  sourceRoot: string;
  sourceRootIdentity: PromotionFsIdentity;
  sourceComponents: string[];
  sourceParentIdentity: PromotionFsIdentity;
  expectedSource: { identity: PromotionFsIdentity; mode: number };
  destinationRoot: string;
  destinationRootIdentity: PromotionFsIdentity;
  destinationComponents: string[];
  destinationParentIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<{ outcome: "applied" | "conflict-after-mutation"; durable: boolean; error: string | null }> {
  const result = decodePromotionResponse(await coreClient.request({
    op: "promotion-bound-install-directory",
    ...options,
    sourceRootIdentity: { dev: options.sourceRootIdentity.dev, ino: options.sourceRootIdentity.ino },
    ...(options.sourceRootIdentity.capability ? { sourceRootCapability: options.sourceRootIdentity.capability } : {}),
    destinationRootIdentity: { dev: options.destinationRootIdentity.dev, ino: options.destinationRootIdentity.ino },
    ...(options.destinationRootIdentity.capability ? { destinationRootCapability: options.destinationRootIdentity.capability } : {}),
  }));
  if ((result.outcome !== "applied" && result.outcome !== "conflict-after-mutation") || typeof result.durable !== "boolean" || (result.error !== null && typeof result.error !== "string")) {
    throw new Error("invalid bound promotion directory install result");
  }
  return { outcome: result.outcome, durable: result.durable, error: result.error as string | null };
}

/** Remove a journal operation only while its parent/leaf identities remain bound. */
export async function boundPromotionRemoveTree(options: {
  root: string;
  rootIdentity: PromotionFsIdentity;
  components: string[];
  parentIdentity: PromotionFsIdentity;
  expectedIdentity: PromotionFsIdentity;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<void> {
  const result = decodePromotionResponse(await coreClient.request({
    op: "promotion-bound-remove-tree",
    ...options,
    rootIdentity: { dev: options.rootIdentity.dev, ino: options.rootIdentity.ino },
    ...(options.rootIdentity.capability ? { rootCapability: options.rootIdentity.capability } : {}),
  }));
  if (result.removed !== true) throw new Error("bound promotion cleanup did not remove its operation");
}

/**
 * Provenance for one app-owned directory created below a trusted parent.
 * Cleanup retains both identities so a parent or leaf replacement cannot be
 * mistaken for the directory that the owner created.
 */
export interface BoundOwnedDirectory {
  path: string;
  parentPath: string;
  identity: PromotionFsIdentity;
  parentIdentity: PromotionFsIdentity;
}

/** Provenance for one app-owned leaf below a retained directory. */
export interface BoundOwnedEntry {
  path: string;
  parentPath: string;
  identity: PromotionFsIdentity;
  parentIdentity: PromotionFsIdentity;
  kind: "file" | "symlink";
}

/** Create an owned directory atomically below a bound parent. */
export async function createOwnedDirectory(
  parentPath: string,
  parentIdentity: PromotionFsIdentity,
  prefix: string,
  testHook?: { stage: string; readyPath: string; releasePath: string },
): Promise<BoundOwnedDirectory> {
  const name = `${prefix}${randomUUID()}`;
  const identity = await boundPromotionCreateDirectory({
    root: parentPath,
    rootIdentity: parentIdentity,
    components: [name],
    parentIdentity,
    requireMissing: true,
    ...(testHook ? { testHook } : {}),
  });
  return {
    path: join(parentPath, name),
    parentPath,
    identity,
    parentIdentity,
  };
}

/** Bind an existing app-owned regular-file or symlink leaf. */
export async function bindOwnedEntry(
  path: string,
  expectedParentIdentity?: PromotionFsIdentity,
  expectedIdentity?: PromotionFsIdentity,
): Promise<BoundOwnedEntry> {
  const parentPath = dirname(path);
  const parentExpected = expectedParentIdentity ?? (() => {
    const metadata = lstatSync(parentPath, { bigint: true });
    if (!metadata.isDirectory() || metadata.isSymbolicLink()) throw new Error("owned entry parent is not a real directory");
    return { dev: String(metadata.dev), ino: String(metadata.ino) };
  })();
  const parentIdentity = await boundPromotionOpenDirectory({
    path: parentPath,
    expectedIdentity: parentExpected,
  });
  const metadata = lstatSync(path, { bigint: true });
  if (!metadata.isFile() && !metadata.isSymbolicLink()) throw new Error("owned entry is not a regular file or symlink");
  const identity = { dev: String(metadata.dev), ino: String(metadata.ino) };
  if (expectedIdentity && (identity.dev !== expectedIdentity.dev || identity.ino !== expectedIdentity.ino)) {
    throw new Error("owned entry identity changed while binding");
  }
  const verifiedParent = await boundPromotionOpenDirectory({
    path: parentPath,
    expectedIdentity: parentIdentity,
  });
  if (verifiedParent.dev !== parentIdentity.dev || verifiedParent.ino !== parentIdentity.ino) {
    throw new Error("owned entry parent identity changed while binding");
  }
  return {
    path,
    parentPath,
    identity,
    parentIdentity: verifiedParent,
    kind: metadata.isSymbolicLink() ? "symlink" : "file",
  };
}

/** Bind an existing app-owned directory and its immediate parent. */
export async function bindOwnedDirectory(
  path: string,
  expectedParentIdentity?: PromotionFsIdentity,
): Promise<BoundOwnedDirectory> {
  const parentPath = dirname(path);
  const pathIdentity = (candidate: string, field: string): PromotionFsIdentity => {
    const metadata = lstatSync(candidate, { bigint: true });
    if (!metadata.isDirectory() || metadata.isSymbolicLink()) throw new Error(`${field} is not a real directory`);
    return { dev: String(metadata.dev), ino: String(metadata.ino) };
  };
  const parentExpected = expectedParentIdentity ?? pathIdentity(parentPath, "owned directory parent");
  const parentIdentity = await boundPromotionOpenDirectory({
    path: parentPath,
    expectedIdentity: parentExpected,
  });
  const identity = await boundPromotionOpenDirectory({
    path,
    expectedIdentity: pathIdentity(path, "owned directory"),
  });
  const verifiedParent = await boundPromotionOpenDirectory({
    path: parentPath,
    expectedIdentity: parentIdentity,
  });
  if (verifiedParent.dev !== parentIdentity.dev || verifiedParent.ino !== parentIdentity.ino) {
    throw new Error("owned directory parent identity changed while binding");
  }
  return { path, parentPath, identity, parentIdentity: verifiedParent };
}

/** Remove an owned directory only through its identity-bound parent. */
export async function removeBoundOwnedDirectory(options: {
  binding: BoundOwnedDirectory;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<void> {
  const { binding } = options;
  const expectedParent = { dev: binding.parentIdentity.dev, ino: binding.parentIdentity.ino };
  let parent: PromotionFsIdentity;
  try {
    parent = await boundPromotionOpenDirectory({
      path: binding.parentPath,
      expectedIdentity: expectedParent,
      ...(binding.parentIdentity.capability ? { capability: binding.parentIdentity.capability } : {}),
    });
  } catch {
    // A native core restart discards in-memory capabilities.  Rebind only by
    // the persisted identity; a replacement parent still fails closed.
    parent = await boundPromotionOpenDirectory({ path: binding.parentPath, expectedIdentity: expectedParent });
  }
  const leafName = basename(binding.path);
  if (!leafName || leafName === "." || leafName === ".." || leafName.includes("/") || leafName.includes("\\")) {
    throw new Error("owned directory leaf name is invalid");
  }
  await boundPromotionRemoveTree({
    root: binding.parentPath,
    rootIdentity: parent,
    components: [leafName],
    parentIdentity: parent,
    expectedIdentity: { dev: binding.identity.dev, ino: binding.identity.ino },
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
}

/** Remove an app-owned leaf only through its identity-bound parent. */
export async function removeBoundOwnedEntry(options: {
  binding: BoundOwnedEntry;
  testHook?: { stage: string; readyPath: string; releasePath: string };
}): Promise<void> {
  const { binding } = options;
  const expectedParent = { dev: binding.parentIdentity.dev, ino: binding.parentIdentity.ino };
  let parent: PromotionFsIdentity;
  try {
    parent = await boundPromotionOpenDirectory({
      path: binding.parentPath,
      expectedIdentity: expectedParent,
      ...(binding.parentIdentity.capability ? { capability: binding.parentIdentity.capability } : {}),
    });
  } catch {
    parent = await boundPromotionOpenDirectory({ path: binding.parentPath, expectedIdentity: expectedParent });
  }
  const leafName = basename(binding.path);
  if (!leafName || leafName === "." || leafName === ".." || leafName.includes("/") || leafName.includes("\\")) {
    throw new Error("owned entry leaf name is invalid");
  }
  await boundPromotionRemoveTree({
    root: binding.parentPath,
    rootIdentity: parent,
    components: [leafName],
    parentIdentity: parent,
    expectedIdentity: { dev: binding.identity.dev, ino: binding.identity.ino },
    ...(options.testHook ? { testHook: options.testHook } : {}),
  });
}

/** True when the capture root is the Git top-level or a folder inside it. */
export function captureRootInRepo(captureRoot: string, gitTopLevel: string): boolean {
  return captureRoot === gitTopLevel || captureRoot.startsWith(gitTopLevel + sep);
}

/** Convenience: the canonical Git top-level directory of a folder. */
export async function gitTopLevel(root: string): Promise<string | null> {
  const res = (await coreClient.request({ op: "git-top-level", root })) as { root: string | null };
  return res.root;
}

/** Convenience: the canonical common Git directory of a folder. */
export async function gitCommonDir(root: string): Promise<string | null> {
  const res = (await coreClient.request({ op: "git-common-dir", root })) as { gitDir: string | null };
  return res.gitDir;
}

/** Convenience: the current HEAD oid, or null when the repo is unborn. */
export async function gitHead(root: string): Promise<string | null> {
  const res = (await coreClient.request({ op: "git-head", root })) as { head: string | null };
  return res.head;
}

/** Convenience: the object format of a repository. */
export async function gitObjectFormat(root: string): Promise<"sha1" | "sha256"> {
  const res = (await coreClient.request({ op: "git-object-format", root })) as { format: "sha1" | "sha256" };
  return res.format;
}

/** Pair-creation disk reserve for Worldline candidates. */
export const MIN_WORLDS_FREE_BYTES = 512 * 1024 * 1024;

/** Free disk bytes on the volume that holds `path`. Returns null on error. */
export async function freeDiskBytes(path: string): Promise<number | null> {
  try {
    const out = await new Promise<string>((res) => {
      execFile("df", ["-k", path], { encoding: "utf8", maxBuffer: 1024 * 1024 }, (_err, stdout) => res(stdout));
    });
    const lines = out.trim().split("\n");
    const header = lines[0]?.split(/\s+/) ?? [];
    // macOS says "Available"; Linux says "Avail".
    const availIdx = header.findIndex((h) => h.startsWith("Avail"));
    const row = lines[1]?.split(/\s+/) ?? [];
    const avail = Number(row[availIdx]);
    return Number.isFinite(avail) ? avail * 1024 : null;
  } catch {
    return null;
  }
}

/** True when the platform provides a reliable recursive watcher. */
export function platformHasRecursiveWatcher(): boolean {
  return process.platform === "darwin" || process.platform === "win32";
}

/** True when the platform binary `sandbox-exec` exists (macOS). */
export function platformHasSandboxExec(): boolean {
  if (process.platform !== "darwin") return false;
  try {
    readFileSync(SANDBOX_EXEC);
    return true;
  } catch {
    return false;
  }
}

/** True when the platform provides copy-on-write clones (`cp -c`). */
export function platformHasCopyOnWrite(): boolean {
  return process.platform === "darwin";
}
